baseURL = 'https://rustun.io/'
languageCode = 'en-us'
title = 'Rustun - Modern VPN Tunnel'
theme = 'rustun'

# Enable multilingual mode
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'Rustun - Modern VPN Tunnel'
    [languages.en.params]
      description = 'High-performance VPN tunnel implementation written in Rust'

  [languages.zh]
    languageName = '中文'
    weight = 2
    title = 'Rustun - 现代 VPN 隧道'
    [languages.zh.params]
      description = 'Rust 编写的高性能 VPN 隧道，用于实现设备互联，异地组网'

[params]
  github = 'https://github.com/smartethnet/rustun'
  version = '1.0.1'
  demo_server = 'https://rustun.beyondnetwork.cn'
  demo_server_addr = 'rustun.demo.beyondnetwork.cn:18080'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Features'
    url = '/#features'
    weight = 2
  [[menu.main]]
    name = 'Download'
    url = '/#download'
    weight = 3
  [[menu.main]]
    name = 'Docs'
    url = 'https://github.com/smartethnet/rustun#readme'
    weight = 4
  [[menu.main]]
    name = 'GitHub'
    url = 'https://github.com/smartethnet/rustun'
    weight = 5

